#!/bin/bash

# Check if there are at least three arguments
if [ "$#" -lt 3 ] || ([ "$1"!="-r" ] && [ "$1"!="-i" ])  
then
    echo "Usage: $0 [-r|-i] <input_file> <output_file>"
    exit 1
fi

python3 src/search.py "$1" "$2" "$3"